{
    "docstring": "",
    "name": "GDALException",
    "namespace": "django.contrib.gis.gdal.error.GDALException",
    "parent_namespace": "django.contrib.gis.gdal.error"
}